#!/usr/bin/env bash
# Bake a self-describing BARO gguf: sources, hardware receipt, and everything
# `tools/baro run` needs to serve the model with no checkout.
#
# usage: tools/bake.sh SRC.gguf DST.gguf ARCH REF_IDS_FILE PROMPT_TOKENS PACK_FLAGS [--kv=... ...]
#   ARCH            one of tools/embed-files.py's arches (qwythos, qwen35moe, spark, ...)
#   REF_IDS_FILE    the ids a rebuilt engine must produce for PROMPT_TOKENS,
#                   generated by the repo-built engine at THIS commit
#   PROMPT_TOKENS   the prompt those ids came from (bench/mtp-prompts/*.tokens)
#   PACK_FLAGS      the pack tool's flags for this model ('' for none)
# env BARO_RUN_ENV   what the model needs to run at all, default
#                    'BARO_MEGA=0 BARO_SPEC=0' (the MoE profile aborts on the
#                    engine's own BARO_MEGA=1 default, so the file carries this)
# env BARO_PACK_TOOL the pack builder to embed, default tools/engine-pack.py
#                    (llama/qwen2/granite dense path); spark2_5 has a per-head
#                    attention gate engine-pack.py refuses, so its bakes need
#                    BARO_PACK_TOOL=tools/spark-pack.py
# env BARO_PROFILE   path to a tools/gen-profile.mojo output for this exact
#                    model, REQUIRED when ARCH=spark: serve/spark.mojo does
#                    `from profile import ...` and the profile is a function
#                    of the gguf (dims, rope, activation), not a repo file, so
#                    embed-files.py cannot find it by walking imports alone
#
# The reference pair is the part that was missing before B1: the closure used to
# reach for .work/ paths the file never carried, so tools/gguf-verify.sh exited 1
# on a bake whose local scratch had been cleaned. A file that verifies itself
# carries its own prompt and its own reference ids.
#
# The extra --kv=baro.hw.* arguments are the baking card's receipt (card, driver,
# ROCm, power cap, the 20-prompt median and the protocol that produced it); pass
# them through, they are what a verifier on another card compares against.
set -euo pipefail
cd "$(dirname "$0")/.."
src=$1; dst=$2; arch=$3; ref=$4; prompt=$5; packflags=$6; shift 6
[ -f "$src" ] || { echo "no source gguf $src" >&2; exit 1; }
[ ! -e "$dst" ] || { echo "destination exists: $dst" >&2; exit 1; }
[ -s "$ref" ] || { echo "no reference ids $ref (run the repo-built engine on $prompt first)" >&2; exit 1; }
[ -s "$prompt" ] || { echo "no prompt token file $prompt" >&2; exit 1; }
# Only what actually enters the file: the kernel closure, the serve Mojo
# modules and the vendored packages. serve/src is the Rust front and is not
# embedded, so another lane editing it must not block a bake.
dirty=$(git status --porcelain -- kernels 'serve/*.mojo' grammar uregex minja latentos)
[ -z "$dirty" ] || { echo "refusing to bake from a dirty source tree:"; echo "$dirty"; exit 1; }
harness=serve/engine.mojo
profile_args=()
if [ "$arch" = spark ]; then
  harness=serve/spark.mojo
  [ -n "${BARO_PROFILE:-}" ] || { echo "ARCH=spark needs BARO_PROFILE=path/to/profile.mojo (tools/gen-profile.mojo output for $src)" >&2; exit 1; }
  [ -f "$BARO_PROFILE" ] || { echo "no profile.mojo at BARO_PROFILE=$BARO_PROFILE" >&2; exit 1; }
  profile_args=(--profile "$BARO_PROFILE")
fi
echo "baking $dst from $src at $(git rev-parse --short HEAD), arch $arch"
./.venv/bin/python3 tools/gguf-embed.py "$src" "$dst" $(tools/embed-files.py --arch "$arch" "${profile_args[@]}") \
  --run-harness="$harness" \
  --run-prompt="$prompt" \
  --run-ref="$ref" \
  --run-pack-tool="${BARO_PACK_TOOL:-tools/engine-pack.py}" \
  --run-env="${BARO_RUN_ENV:-BARO_MEGA=0 BARO_SPEC=0}" \
  --run-pack-flags="$packflags" \
  "$@"
echo "verify it with: tools/baro verify $dst"
