#!/usr/bin/env python3
"""Kernel census: every `amar_*` device kernel under kernels/ must be reachable
from the engine registry (serve/registry.mojo), a bench, or a test. Emits
docs/KERNELS.md and exits non-zero on an orphan.

usage: tools/kernel-census.py [--check]   (--check: no write, just gate)
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
KDIR, REG = ROOT / "kernels", ROOT / "serve" / "registry.mojo"
DEF = re.compile(r"^(?:def|fn) (amar_[a-z0-9_]+)\[?", re.M)
PARAMS = re.compile(r"^(?:def|fn) amar_[a-z0-9_]+\[([^\]]*)\]", re.M | re.S)

def scan():
    kernels = {}
    for f in sorted(KDIR.glob("*.mojo")):
        if f.name.startswith("test_"):
            continue
        src = f.read_text()
        for m in DEF.finditer(src):
            name = m.group(1)
            pm = re.search(r"^(?:def|fn) " + name + r"\[([^\]]*)\]", src, re.M | re.S)
            params = " ".join(pm.group(1).split()) if pm else ""
            kernels[name] = {"file": f.name, "params": params, "used": []}
    users = [REG, ROOT / "serve" / "engine.mojo", KDIR / "amarbaro.mojo"]
    users += sorted((ROOT / "bench").glob("*.mojo")) + sorted(KDIR.glob("test_*.mojo"))
    for u in users:
        src = u.read_text()
        for name in kernels:
            if re.search(r"\b" + name + r"\b", src):
                kernels[name]["used"].append(u.relative_to(ROOT).as_posix())
    return kernels

def render(kernels):
    reg = REG.read_text()
    roles = {}
    for m in re.finditer(r"^comptime ([a-z0-9_]+) = (amar_[a-z0-9_]+)", reg, re.M):
        roles.setdefault(m.group(2), []).append(m.group(1))
    for m in re.finditer(r"(amar_[a-z0-9_]+)\[", reg):
        roles.setdefault(m.group(1), [])
    out = ["# Kernel census", "",
           "Generated by `tools/kernel-census.py`; do not hand-edit. Every `amar_*` kernel",
           "must be reachable from `serve/registry.mojo`, a bench, or a test.", "",
           "| kernel | file | template params | registry roles | used by |", "|---|---|---|---|---|"]
    for name, k in sorted(kernels.items(), key=lambda kv: (kv[1]["file"], kv[0])):
        r = ", ".join(roles.get(name, [])) or ("gemm_q8 dispatch" if name == "amar_matmul_skinny_q8row" else "")
        out.append(f"| `{name}` | `{k['file']}` | `{k['params']}` | {r} | {', '.join(k['used'])} |")
    return "\n".join(out) + "\n"

kernels = scan()
orphans = [n for n, k in kernels.items() if not k["used"]]
if "--check" not in sys.argv:
    (ROOT / "docs" / "KERNELS.md").write_text(render(kernels))
print(f"{len(kernels)} kernels, {sum(1 for k in kernels.values() if REG.name in ''.join(k['used']))} in registry, {len(orphans)} orphans")
for n in orphans:
    print("ORPHAN:", n, kernels[n]["file"])
sys.exit(1 if orphans else 0)
