#!/usr/bin/env python3
"""Structural id for a GGUF: a hash of exactly what the served engine
compiles in for this checkpoint's shape, read from the GGUF header and
tensor-info table only (never tensor bytes, never weights) -- so two
checkpoints of one shape (Qwen2.5-7B and Qwen2.5-Coder-7B) hash to the same
id and a copy with one compiled-in dimension edited hashes to a different
one. Quant format and individual weight values never enter the id: neither
serve/engine.mojo nor serve/spark.mojo reads quant type at compile time (the
pack tool dequantizes at pack-build time, keyed separately by GGUF sha, item
2), so folding it into the id would fragment the engine cache across
checkpoints that build the identical binary.

Two engine families, two different sources of compiled-in dims (item 3):

  qwen35 / qwen35moe -> serve/engine.mojo, `-D BARO_MODEL=<arch>`. The
  compiled dims are the FIXED comptime constants in serve/model_qwen35.mojo /
  serve/model_qwen35moe.mojo, selected by that one flag -- nothing about a
  specific checkpoint's shape is read into the binary. The id is therefore
  just a hash of the flag; what IS checked is that this gguf's own declared
  shape (H/N_LAYERS/NQH/NKVH/HD/VOCAB) agrees with those hardcoded constants,
  refusing loudly (P1, bench/PROTOCOL-RULES.md: no silently-inert parameter)
  rather than serving a checkpoint the compiled profile does not fit.

  llama / qwen2 / granite / spark2_5 -> serve/spark.mojo + a profile.mojo
  generated by tools/gen-profile.mojo. The id hashes exactly the fields that
  script emits (mirrored here so this needs no `mojo` toolchain to run):
  H, FFN, N_LAYERS, NQH, NKVH, HD, NORM_EPS, the full-attention and SWA rope
  configs (SWA compressed to its period/phase, same as gen-profile), VOCAB,
  TIE_EMBED, QKV_BIAS, HAS_GATE, and the per-arch activation/rope-family/
  granite-mult/scale facts (a function of `arch` alone, included for
  discrimination against a future arch reusing these same dims).

Usage: tools/model-id.py MODEL.gguf [--json]
Prints the id on stdout and exits 0, or on stderr "unsupported: <reason>"
and exits 1 for an architecture, tokenizer, or shape mismatch serve/*.mojo
cannot run (item 3, briefs/2026-09-16-baro-serve-cache-lane.md).
"""
import hashlib
import json
import math
import re
import sys
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
spec = spec_from_file_location("ge", HERE / "gguf-extract.py")
ge = module_from_spec(spec)
spec.loader.exec_module(ge)

QWEN35_MODEL_FILE = {
    "qwen35": ROOT / "serve/model_qwen35.mojo",
    "qwen35moe": ROOT / "serve/model_qwen35moe.mojo",
}
# tools/gen-profile.mojo's own arch tables (is_rope_neox_arch/is_rope_norm_arch,
# is_gelu_arch/is_silu_arch): the only arches it can emit a profile for.
SPARK_ARCHES = {"llama", "qwen2", "granite", "spark2_5"}
# serve/tokenizer.mojo's pre-tokenizer regex table (__init__, around line 251).
TOKENIZER_PRE_SUPPORTED = {
    "qwen2", "deepseek-r1-qwen", "qwen35", "llama3", "llama-bpe",
    "spark2_5", "gpt-2", "default", "granite-docling",
}


def akv(kv, arch, name, default=None):
    """llama.cpp convention: every dense-family key rides under `<arch>.*`."""
    for k in (f"{arch}.{name}", name):
        if k in kv:
            return kv[k]
    return default


def vocab_of(infos):
    """token_embd.weight's logical (torch) shape is [VOCAB, H] -- gguf-extract.py
    stores dims innermost-first, so the reversed (logical) shape's index 0 is
    VOCAB, not 1 (tools/gen-profile.mojo's own `embd_dims[1]` reads the RAW,
    un-reversed dims, where index 1 is the outer/VOCAB dim; this function
    reverses first, so its own index is 0, not 1 -- verified against the
    known VOCAB=248320 for qwen35, 2026-09-16)."""
    dims = infos.get("token_embd.weight", (None,))[0]
    if not dims or len(dims) != 2:
        return None
    return list(reversed(dims))[0]


def find_swa_period(pattern):
    """Mirrors tools/gen-profile.mojo's find_swa_period."""
    n = len(pattern)
    for period in range(1, 9):
        for phase in range(period):
            if all((pattern[i] == 1) == (i % period != phase) for i in range(n)):
                return period, phase
    raise ValueError("sliding_window_pattern is not periodic in [1,8]")


def parse_comptime_ints(path):
    """H/N_LAYERS/NQH/NKVH/HD/VOCAB out of a model_qwen35*.mojo file, the same
    plain `comptime NAME = 1234` lines gen-profile.mojo itself would emit."""
    text = path.read_text()
    out = {}
    for name in ("H", "N_LAYERS", "NQH", "NKVH", "HD", "VOCAB"):
        m = re.search(rf"^comptime {name} = (\d+)\s*$", text, re.M)
        if m:
            out[name] = int(m.group(1))
    return out


def qwen35_fields(kv, infos, arch):
    """Validates this checkpoint's own declared shape against the fixed
    compiled profile for `arch`; raises SystemExit(1) on a mismatch. Returns
    the (tiny) hashed field set: just which of the two fixed profiles this
    is, since neither is generated per-checkpoint (see module docstring)."""
    model_file = QWEN35_MODEL_FILE[arch]
    compiled = parse_comptime_ints(model_file)
    declared = {
        "H": int(akv(kv, arch, "embedding_length", 0) or 0),
        "N_LAYERS": int(akv(kv, arch, "block_count", 0) or 0),
        "NQH": int(akv(kv, arch, "attention.head_count", 0) or 0),
        "NKVH": int(akv(kv, arch, "attention.head_count_kv", 0) or 0),
        "HD": int(akv(kv, arch, "attention.key_length", 0) or 0),
        "VOCAB": vocab_of(infos) or 0,
    }
    # N_LAYERS: gguf's own block_count may legitimately exceed the compiled
    # depth -- an MTP draft block rides as one extra blk.N (Qwythos-9B-v2-MTP:
    # block_count 33, compiled N_LAYERS 32, PASSES verify; ~/Brain/mojo-baro/
    # mtp-landed.md) -- so only UNDER-count is a hard mismatch; every other
    # field must match exactly, since a silent wrong H/head-count/vocab
    # corrupts every buffer shape in the compiled engine (bench/PROTOCOL-
    # RULES.md P1).
    mismatches = [
        f"{k}: gguf declares {declared[k]}, {model_file.name} compiles {compiled.get(k)}"
        for k in compiled
        if (declared[k] < compiled[k] if k == "N_LAYERS" else compiled[k] != declared[k])
    ]
    if mismatches:
        sys.exit("unsupported: this checkpoint's own shape does not match the fixed "
                  f"{model_file.name} profile ({arch} has only one compiled shape, "
                  "not one generated per checkpoint): " + "; ".join(mismatches))
    return {"BARO_MODEL": arch}


def spark_fields(kv, infos, arch):
    """Mirrors tools/gen-profile.mojo's own field computation exactly, so the
    id changes precisely when a re-run of gen-profile would emit a different
    profile.mojo. No mojo toolchain needed: same arithmetic, pure Python."""
    h = int(akv(kv, arch, "embedding_length", 0) or 0)
    ffn = int(akv(kv, arch, "feed_forward_length", 0) or 0)
    n_layers = int(akv(kv, arch, "block_count", 0) or 0)
    nqh = int(akv(kv, arch, "attention.head_count", 0) or 0)
    nkvh = int(akv(kv, arch, "attention.head_count_kv", 0) or 0)
    hd = int(akv(kv, arch, "attention.key_length", 0) or (h // nqh if nqh else 0))
    norm_eps = float(akv(kv, arch, "attention.layer_norm_rms_epsilon", 1e-6))
    nrot_full = int(akv(kv, arch, "rope.dimension_count", hd) or hd)
    base_full = float(akv(kv, arch, "rope.freq_base", 10000.0))

    pattern = akv(kv, arch, "attention.sliding_window_pattern", []) or []
    if isinstance(pattern, list) and pattern and all(isinstance(x, int) for x in pattern):
        swa_win = int(akv(kv, arch, "attention.sliding_window", 0) or 0)
        nrot_swa = int(akv(kv, arch, "rope.dimension_count_swa", nrot_full) or nrot_full)
        base_swa = float(akv(kv, arch, "rope.freq_base_swa", base_full))
        swa_period, swa_full_phase = find_swa_period(pattern)
    else:
        swa_win, nrot_swa, base_swa, swa_period, swa_full_phase = 0, nrot_full, base_full, 1, 0

    tie_embed = "output.weight" not in infos
    qkv_bias = "blk.0.attn_q.bias" in infos
    has_gate = "blk.0.attn_gate.weight" in infos
    granite_mult = arch == "granite"
    default_attn_scale = 1.0 / math.sqrt(hd) if hd else 0.0
    attn_scale = float(akv(kv, arch, "attention.scale", default_attn_scale)) if granite_mult else default_attn_scale

    return {
        "arch": arch,
        "H": h, "FFN": ffn, "N_LAYERS": n_layers, "NQH": nqh, "NKVH": nkvh, "HD": hd,
        "NORM_EPS": norm_eps, "NROT_FULL": nrot_full, "BASE_FULL": base_full,
        "NROT_SWA": nrot_swa, "BASE_SWA": base_swa, "SWA_WIN": swa_win,
        "SWA_PERIOD": swa_period, "SWA_FULL_PHASE": swa_full_phase,
        "ROPE_NEOX": arch in ("spark2_5", "qwen2"),
        "QKV_BIAS": qkv_bias, "HAS_GATE": has_gate, "TIE_EMBED": tie_embed,
        "ACTIVATION_GELU": arch == "spark2_5",
        "GRANITE_MULT": granite_mult,
        "ATTN_SCALE": attn_scale,
        "EMBED_SCALE": float(akv(kv, arch, "embedding_scale", 1.0)),
        "RESIDUAL_SCALE": float(akv(kv, arch, "residual_scale", 1.0)),
        "LOGIT_SCALE": float(akv(kv, arch, "logit_scale", 1.0)),
        "VOCAB": vocab_of(infos),
    }


def resolve(model_path):
    """Returns (model_id, fields, arch, engine), or exits 1 with the refusal
    reason on stderr (unsupported architecture, tokenizer, or shape)."""
    f, infos, data_start, kv = ge.parse(model_path)

    arch = kv.get("general.architecture")
    if not arch:
        sys.exit("unsupported: no general.architecture key in this gguf")

    pre = kv.get("tokenizer.ggml.pre", kv.get("tokenizer.ggml.model", "default"))
    if pre not in TOKENIZER_PRE_SUPPORTED:
        sys.exit(f"unsupported: tokenizer.ggml.pre={pre!r} has no pre-tokenizer "
                  f"regex in serve/tokenizer.mojo (supported: {sorted(TOKENIZER_PRE_SUPPORTED)})")

    if arch in QWEN35_MODEL_FILE:
        engine = "engine"
        fields = qwen35_fields(kv, infos, arch)
    elif arch in SPARK_ARCHES:
        engine = "spark"
        fields = spark_fields(kv, infos, arch)
    else:
        sys.exit(f"unsupported: architecture {arch!r} has no engine module "
                  f"(serve/engine.mojo covers {sorted(QWEN35_MODEL_FILE)}, "
                  f"serve/spark.mojo covers {sorted(SPARK_ARCHES)})")

    blob = json.dumps({"engine": engine, **fields}, sort_keys=True)
    digest = hashlib.sha256(blob.encode()).hexdigest()[:16]
    model_id = f"{arch}-{digest}"
    return model_id, fields, arch, engine


def main():
    argv = [a for a in sys.argv[1:] if not a.startswith("--")]
    as_json = "--json" in sys.argv
    if not argv:
        sys.exit("usage: tools/model-id.py MODEL.gguf [--json]")
    model_id, fields, arch, engine = resolve(argv[0])
    if as_json:
        print(json.dumps({"id": model_id, "arch": arch, "engine": engine, "fields": fields}, indent=1))
    else:
        print(model_id)


if __name__ == "__main__":
    main()
