#!/usr/bin/env python3
"""Independent numpy oracle for the C3 fix round's gate 2 chi-square check
(bench/chat-protocol.md "C3 fix round: host top-p mass target").

For each (row, config) computes the CORRECT retained candidate set (sorted
descending by logit, top-k first if on, then a top-p mass cutoff at the raw
(not ceil'd) mass target top_p * Z clamped to [the top-1 token's own mass,
Z], then a min-p floor) and its tempered softmax distribution, independent
of both serve/sample_ref.mojo and kernels/sample.mojo.

Writes one file per (row, config): first line = candidate count, then one
"id prob" line per candidate, in descending-logit order (rank 0 first).
kernels/test_sample_device.mojo reads these back to build the chi-square
target and a token-id -> rank map for binning device draws.

Usage: tools/sample-nucleus-oracle.py ROW.bin OUT_PREFIX
  writes OUT_PREFIX-<config-slug>.txt for every CONFIGS entry.

Rows are not committed (real decode logits, regenerated by a one-shot engine
run per prompt, same as .work/draft-logits.bin -- see
kernels/test_sample_device.mojo's docstring for the exact commands). Run
this against each row before running kernels/test_sample_device.mojo's gate
2; its output also lives under .work/, regenerable, not committed.
"""
import sys
import numpy as np

CONFIGS = [
    ("T1_k0_p1", 1.0, 0, 1.0, 0.0),
    ("T0.8_k30_p1", 0.8, 30, 1.0, 0.0),
    ("T0.7_k20_p0.8", 0.7, 20, 0.8, 0.0),
    ("T1.3_k12_p0.9_minp0.05", 1.3, 12, 0.9, 0.05),
    ("T0.5_k0_p0.6", 0.5, 0, 0.6, 0.0),
]


def nucleus(x, T, k, p, minp):
    o = np.argsort(-x, kind="stable")
    xs = x[o]
    lmax = xs[0]
    e = np.exp(xs - lmax)
    nvalid = x.size
    mk = nvalid
    if k > 0 and k < nvalid:
        mk = k
    if p < 1.0:
        zc = float(e[:mk].sum())
        w = p * zc
        w = max(1.0, min(w, zc))  # clamp: [top-1 token's own mass (1.0), zc]
        cum = np.cumsum(e[:mk])
        m = int(np.searchsorted(cum, w) + 1)
        mk = min(m, mk)
    if minp > 0:
        mpe = min(minp, 1.0)
        keep = e[:mk] >= mpe
        m = int(np.argmin(keep)) if not keep.all() else mk
        mk = max(m, 1)
    ids = o[:mk]
    ev = np.exp((xs[:mk] - lmax) / T)
    probs = ev / ev.sum()
    return ids, probs


BIN_CAP = 60  # explicit rank bins; a "rest" bin absorbs everything past this
# so a chi-square over an untruncated (T1 k0 p1) real-vocab distribution has
# a manageable, non-degenerate bin count instead of 248320 near-empty bins.


def main():
    row_path, out_prefix = sys.argv[1], sys.argv[2]
    x = np.fromfile(row_path, dtype=np.float32).astype(np.float64)
    for slug, T, k, p, minp in CONFIGS:
        ids, probs = nucleus(x, T, k, p, minp)
        n_explicit = min(len(ids), BIN_CAP)
        rest_mass = float(probs[n_explicit:].sum())
        with open(f"{out_prefix}-{slug}.txt", "w") as f:
            f.write(f"{n_explicit} {rest_mass:.10e}\n")
            for i, pr in zip(ids[:n_explicit], probs[:n_explicit]):
                f.write(f"{int(i)} {pr:.10e}\n")
        print(f"{slug}: {len(ids)} candidates ({n_explicit} explicit + rest {rest_mass:.6f}), top prob {probs[0]:.6f}")


if __name__ == "__main__":
    main()
